[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/.netlify/*"
  to = "/.netlify/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
